# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8edab25c1852d86fb8f39a85fc62f243f92cc8b33fa6f5f01e60da31f732566ad1ce4ba5143f43e9f852bffdf84a7f96d6b9031b85c908f5cabdbde1aba5f94d

test:
  secret_key_base: edc798a1c15eecd61331b85f537fbeca8a897be7bd732d1d3f1db7a98b10c232a012cac7478363f7b8f1f1667b60680e053948d26fbd1bdefba78bb804a605a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4b46acb2313db8001c8baf25f352a3bab3f90e8d267c5e02161b108b50eb6e4abd35ebaaa57eb7d7ffca634c0a1c6c4f2136efff90b95e8d8d187ee7ba66596f
